package com.github.upcraftlp.heartsplus;

import com.github.upcraftlp.heartsplus.proxy.CommonProxy;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(
        certificateFingerprint = Reference.FINGERPRINT_KEY,
        name = Reference.MODNAME,
        version = Reference.VERSION,
        acceptedMinecraftVersions = Reference.MCVERSIONS,
        modid = Reference.MODID,
        dependencies = Reference.DEPENDENCIES,
        updateJSON = Reference.UPDATE_JSON
)
public class Main {

    @Mod.Instance(Reference.MODID)
    public static Main INSTANCE;

    @SidedProxy(clientSide = Reference.CLIENTPROXY, serverSide = Reference.SERVERPROXY)
    public static CommonProxy proxy;

    private static final Logger log = LogManager.getLogger(Reference.MODID);

    public static Logger getLogger() {
        return log;
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.authorList = Reference.authors;
        data.credits = Reference.CREDITS;
        data.description = Reference.MOD_DESCRIPTION;
        data.url = Reference.WEBSITE;
        proxy.preInit(event);

        log.info("Pre-Initialization finished.");
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.init(event);

        log.info("Initialization finished.");
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        proxy.postInit(event);
        log.info("Post-Initialization finished.");
    }

    @Mod.EventHandler
    public void onServerStarting(FMLServerStartingEvent event) {
        proxy.serverStarting(event);
        log.info("Taking over the world!");
    }

}
